import{useEffect,useMemo,useState}from'react';import{Activity,BookOpen,Box,ChevronRight,Cloud,Copy,Database,KeyRound,LayoutDashboard,Loader2,LogOut,Pencil,Plus,RefreshCw,ShieldCheck,Sparkles,X}from'lucide-react';import{API,AccessKey,Bucket,BucketDetail,Overview,Session}from'./api';import{Brand}from'./Brand';
import{buildAgentPrompt}from'./agentPrompt';
import{FullDocsPage}from'./FullDocsPage';
import{OOBE,StoragePage}from'./StorageSetup';
import{RiskDialog}from'./RiskDialog';
import{ObjectExplorer}from'./ObjectExplorer';
import{APP_VERSION,hasVersionHold,useVersionHold}from'./VersionGuard';

type Page='overview'|'buckets'|'storage'|'access'|'agent'|'docs'|'settings';
const fmt=(n=0)=>n>=1<<30?`${(n/(1<<30)).toFixed(1)} GB`:n>=1<<20?`${(n/(1<<20)).toFixed(1)} MB`:`${n} B`;
const nav=[['overview','总览',LayoutDashboard],['buckets','虚拟桶',Box],['storage','存储源',Database],['access','访问控制',KeyRound],['agent','Agent 接入',Sparkles],['docs','接入文档',BookOpen],['settings','平台设置',ShieldCheck]] as const;

export default function App(){const[session,setSession]=useState<Session>();const[sessionError,setSessionError]=useState('');const[page,setPage]=useState<Page>('overview');const[notice,setNotice]=useState('');useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);const loadSession=()=>new API().session().then(value=>{setSession(value);setSessionError('')}).catch(e=>setSessionError(e.message||'无法连接管理服务'));useEffect(()=>{loadSession();const unauthorized=()=>loadSession();window.addEventListener('rvs-unauthorized',unauthorized);return()=>window.removeEventListener('rvs-unauthorized',unauthorized)},[]);if(!session)return sessionError?<div className="boot-screen"><ErrorBox text={sessionError} retry={loadSession}/></div>:<BootScreen/>;if(!session.authenticated)return <Login oidcReady={session.oidc_configured}/>;if(session.setup_required)return <OOBE email={session.email} onComplete={loadSession}/>;return <div className="shell"><aside><Brand/><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{if(hasVersionHold()){setNotice('请先完成或关闭当前操作，再切换页面');return}setPage(id)}} title={label} aria-label={label}><Icon size={18}/><span>{label}</span>{page===id&&<ChevronRight className="chev" size={15}/>}</button>)}</nav><div className="side-foot"><div className="identity"><span>{session.email}</span><small>OIDC 管理员 · VirSree v{APP_VERSION}</small></div><div className="live">集中管理入口</div><button aria-label="退出管理台" title="退出管理台" onClick={async()=>{if(hasVersionHold()){setNotice('请先安全保存当前内容，再退出');return}await new API().logout();setSession({...session,authenticated:false})}}><LogOut size={16}/>退出管理台</button></div></aside><main><Header page={page}/><section className="content">{page==='overview'&&<OverviewPage token=""/>} {page==='buckets'&&<BucketsPage token="" notify={setNotice}/>} {page==='storage'&&<StoragePage notify={setNotice}/>} {page==='access'&&<AccessPage token=""/>} {page==='agent'&&<AgentPage token="" notify={setNotice}/>} {page==='docs'&&<FullDocsPage/>} {page==='settings'&&<SettingsPage token=""/>}</section></main>{notice&&<div className="toast" role="status" aria-live="polite"><ShieldCheck size={17}/>{notice}<button onClick={()=>setNotice('')}><X size={15}/></button></div>}</div>}

function BootScreen(){return <div className="boot-screen"><div className="boot-mark"><Brand/></div><Loader2 className="spin"/><p>正在唤醒 VirSree…</p></div>}
function Login({oidcReady}:{oidcReady:boolean}){const authError=new URLSearchParams(location.search).get('auth_error');return <div className="login"><div className="login-art"><Brand/><div><p className="eyebrow">PRIVATE STORAGE, CULTIVATED</p><h1>让每一个应用<br/>拥有自己的存储边界。</h1><p>一个集中网关，多种私有存储源。权限、配额、签名与审计清晰生长。</p></div><div className="route-line"><span>APP</span><i/><span>VIRSREE</span><i/><span>PRIVATE STORAGE</span></div></div><section className="login-panel"><div><p className="eyebrow">CONSOLE ACCESS</p><h2>欢迎回来</h2><p>使用管理员白名单内的邮箱继续。</p></div>{authError&&<p className="form-error">{authError}</p>}<a className={`primary oidc-button ${oidcReady?'':'disabled'}`} href={oidcReady?'/auth/login':undefined}>使用 OIDC 登录 <ChevronRight size={17}/></a><small>{oidcReady?'通过 OIDC 安全验证，不在本站保存密码':'OIDC 尚未在服务器配置'}</small></section></div>}
function Header({page}:{page:Page}){const title=nav.find(n=>n[0]===page)?.[1];return <header><div><span className="crumb">VirSree by Rosemary /</span><h1>{title}</h1></div><div className="gateway"><Activity size={16}/><div><strong>Gateway</strong><span>统一入口 · 文件直传</span></div></div></header>}
function useData(token:string,kind:'overview'|'buckets'|'access'){
  const api=useMemo(()=>new API(token),[token]);
  const[overview,setOverview]=useState<Overview>();
  const[buckets,setBuckets]=useState<Bucket[]>([]);
  const[keys,setKeys]=useState<AccessKey[]>([]);
  const[loading,setLoading]=useState(true);
  const[error,setError]=useState('');
  const reload=()=>{
    setError('');
    const requests=kind==='overview'?[api.overview()]:kind==='buckets'?[api.overview(),api.buckets()]:[api.buckets(),api.keys()];
    Promise.all(requests).then(values=>{
      if(kind==='overview')setOverview(values[0] as Overview);
      if(kind==='buckets'){setOverview(values[0] as Overview);setBuckets(values[1] as Bucket[]||[])}
      if(kind==='access'){setBuckets(values[0] as Bucket[]||[]);setKeys(values[1] as AccessKey[]||[])}
    }).catch(e=>setError(e.message)).finally(()=>setLoading(false));
  };
  useEffect(reload,[api,kind]);
  return{api,overview,buckets,keys,loading,error,reload};
}
function Loading(){return <div className="skeletons"><i/><i/><i/><i/></div>}
function ErrorBox({text,retry}:{text:string;retry?:()=>void}){return <div className="error" role="alert"><ShieldCheck/>无法读取平台数据：{text}{retry&&<button className="ghost" onClick={retry}>重试</button>}</div>}
function OverviewPage({token}:{token:string}){const d=useData(token,'overview');if(d.loading)return <Loading/>;if(d.error)return <ErrorBox text={d.error} retry={d.reload}/>;const o=d.overview!;const used=o.used_bytes+o.reserved_bytes;const pct=Math.min(100,o.total_quota?used/o.total_quota*100:0);return <><div className="hero"><div><p className="eyebrow">CONTROL PLANE</p><h2>存储秩序，清晰生长。</h2><p>所有应用请求由网关集中治理，文件数据通过短期签名直达真实私有桶。</p></div><button className="icon-button" onClick={d.reload}><RefreshCw size={17}/></button></div><div className="metrics"><Metric label="虚拟桶" value={o.bucket_count} note="隔离命名空间" icon={<Box/>}/><Metric label="已管理对象" value={o.object_count} note="映射关系有效" icon={<Database/>}/><Metric label="活跃密钥" value={o.active_key_count} note="可独立撤销" icon={<KeyRound/>}/><Metric label="后端状态" value={o.backend_ready?'Ready':'待配置'} note="真实桶保持私有" icon={<Cloud/>}/></div><div className="grid2"><article className="card capacity"><div className="card-title"><div><span>平台总空间</span><strong>{fmt(used)} <small>/ {fmt(o.total_quota)}</small></strong></div><span>{pct.toFixed(1)}%</span></div><div className="bar"><i style={{width:`${pct}%`}}/></div><div className="legend"><span><i className="used"/>已使用 {fmt(o.used_bytes)}</span><span><i className="reserved"/>上传预留 {fmt(o.reserved_bytes)}</span><span>已分配 {fmt(o.allocated_quota)}</span></div></article><article className="card flow"><div className="card-title"><div><span>请求路径</span><strong>控制集中，数据直达</strong></div></div><div className="flow-row"><div>应用程序<small>虚拟 AK/SK</small></div><i/><div className="accent">VirSree 网关<small>鉴权 · 配额 · 签名</small></div><i className="dashed"/><div>私有 S3<small>文件字节直传</small></div></div></article></div></>}
function Metric({label,value,note,icon}:{label:string;value:string|number;note:string;icon:any}){return <article className="metric"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}

function BucketsPage({token,notify}:{token:string;notify:(s:string)=>void}){const d=useData(token,'buckets');const[open,setOpen]=useState(false);const[secret,setSecret]=useState<any>();const[selected,setSelected]=useState<Bucket>();if(d.loading&&!secret)return <Loading/>;if(d.error&&!secret)return <ErrorBox text={d.error} retry={d.reload}/>;if(selected)return <BucketManager api={d.api} bucket={selected} close={()=>{setSelected(undefined);d.reload()}} notify={notify}/>;return <><div className="section-head"><div><p className="eyebrow">VIRTUAL NAMESPACES</p><h2>虚拟桶</h2><p>每个桶拥有独立命名空间、容量限制、状态和访问凭据。</p></div><button className="primary small" onClick={()=>setOpen(true)}><Plus size={16}/>创建虚拟桶</button></div>{!d.buckets.length?<Empty title="还没有虚拟桶" text="创建第一个隔离存储空间，真实文件仍落在受管的私有存储源。"/>:<div className="bucket-grid">{d.buckets.map(b=>{const pct=b.quota_unlimited?0:Math.min(100,(b.used_bytes+b.reserved_bytes)/b.quota_bytes*100);return <article className="bucket" key={b.id}><div className="bucket-top"><div className="bucket-icon"><Box/></div><span className={`pill ${b.visibility}`}>{b.visibility==='public'?'公开映射':'私有'}</span></div><h3>{b.name}</h3><code>s3://{b.slug}</code><div className="bucket-usage"><span>{fmt(b.used_bytes+b.reserved_bytes)} / {b.quota_unlimited?'∞ 无上限':fmt(b.quota_bytes)}</span><span>{b.quota_unlimited?'UNLIMITED':`${pct.toFixed(1)}%`}</span></div><div className={`bar ${b.quota_unlimited?'unlimited':''}`}><i style={{width:`${pct}%`}}/></div><footer><span>{new Date(b.created_at).toLocaleDateString()}</span><button onClick={()=>setSelected(b)}>管理 <ChevronRight size={14}/></button></footer></article>})}</div>}{open&&<CreateBucket api={d.api} canUnlimited={Boolean(d.overview?.primary_source_unlimited)} close={()=>setOpen(false)} done={v=>{setSecret(v);setOpen(false);d.reload();notify('虚拟桶已创建')}}/>}{secret&&<OneTimeSecret data={secret} close={()=>setSecret(undefined)}/>}</>}

function BucketManager({api,bucket,close,notify}:{api:API;bucket:Bucket;close:()=>void;notify:(s:string)=>void}){
  const [detail,setDetail]=useState<BucketDetail>();
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  const [editing,setEditing]=useState(false);
  const load=()=>{setLoading(true);setError('');api.bucketDetail(bucket.slug).then(setDetail).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
  useEffect(load,[api,bucket.slug]);
  const current=detail?.bucket||bucket;
  return <><div className="section-head"><div><button className="back" onClick={close}>← 返回虚拟桶</button><p className="eyebrow">BUCKET CONTROL PLANE</p><h2>{current.name}</h2><p><code>s3://{current.slug}</code> · 配置、接入信息与对象运维</p></div><div className="detail-actions"><button className="ghost" disabled={!detail} onClick={()=>setEditing(true)}><Pencil size={15}/>编辑桶</button><button className="ghost" onClick={load}><RefreshCw size={15}/>刷新</button></div></div>
  {loading&&!detail?<Loading/>:error?<ErrorBox text={error} retry={load}/>:detail&&<><div className="bucket-detail-grid"><article><span>当前状态</span><strong className={`detail-status ${detail.status}`}>{detail.status==='ready'?'可用':'存储不可用'}</strong><small>{detail.metrics.object_count} 个对象 · {detail.metrics.active_key_count} 个活跃密钥</small></article><article><span>容量限制</span><strong>{current.quota_unlimited?'∞ 无上限':fmt(current.quota_bytes)}</strong><small>已用与预留 {fmt(current.used_bytes+current.reserved_bytes)}</small></article><article><span>S3 接入点</span><code>{detail.s3_endpoint}</code><small>Region · {detail.region}</small></article><article><span>控制 API</span><code>{detail.api_endpoint}</code><small>{detail.metrics.active_public_link_count} 个活跃公开链接</small></article></div>{detail.allocations.length>0&&<article className="allocation-strip"><strong>对象分布</strong>{detail.allocations.map(a=><span key={a.source_id||'legacy'}><i>{a.source_kind.toUpperCase()}</i>{a.source_name}<small>{a.object_count} 个 · {fmt(a.used_bytes)}</small></span>)}</article>}</>}
  {editing&&detail&&<EditBucket api={api} detail={detail} close={()=>setEditing(false)} done={()=>{setEditing(false);load();notify('虚拟桶配置已更新')}}/>}
  <ObjectExplorer api={api} bucket={bucket.slug} notify={notify}/></>;
}
function BucketFormFields({name,setName,quota,setQuota,visibility,setVisibility,unlimited,setUnlimited,canUnlimited}:{name:string;setName:(v:string)=>void;quota:number;setQuota:(v:number)=>void;visibility:string;setVisibility:(v:string)=>void;unlimited:boolean;setUnlimited:(v:boolean)=>void;canUnlimited:boolean}){return <><label>显示名称<input required value={name} onChange={e=>setName(e.target.value)} placeholder="媒体资源"/></label><div className="split"><label>空间上限（GB）<input type="number" min="1" disabled={unlimited} required={!unlimited} value={quota} onChange={e=>setQuota(+e.target.value)}/><span className={`inline-check ${!canUnlimited?'disabled':''}`}><input type="checkbox" checked={unlimited} disabled={!canUnlimited} onChange={e=>setUnlimited(e.target.checked)}/> 无限容量</span><small>{canUnlimited?'仅在最高优先级存储源无限时可用':'最高优先级存储源为有限容量'}</small></label><label>访问模式<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="private">私有</option><option value="public">公开映射</option></select></label></div></>}
function EditBucket({api,detail,close,done}:{api:API;detail:BucketDetail;close:()=>void;done:()=>void}){
  const b=detail.bucket;
  const[name,setName]=useState(b.name);
  const[quota,setQuota]=useState(Math.max(1,b.quota_bytes/(1<<30)));
  const[visibility,setVisibility]=useState(b.visibility);
  const[unlimited,setUnlimited]=useState(b.quota_unlimited);
  const[busy,setBusy]=useState(false);
  const[error,setError]=useState('');
  const[confirmPrivate,setConfirmPrivate]=useState(false);
  const save=async()=>{
    setBusy(true);setError('');
    try{await api.updateBucket(b.slug,{name,visibility,quota_bytes:unlimited?0:Math.round(quota*(1<<30)),quota_unlimited:unlimited});done()}
    catch(e:any){setError(e.message||'保存失败');setConfirmPrivate(false)}
    finally{setBusy(false)}
  };
  return <><Modal title="编辑虚拟桶" close={close}><form className="form" onSubmit={e=>{e.preventDefault();if(b.visibility==='public'&&visibility==='private')setConfirmPrivate(true);else void save()}}><div className="immutable-slug"><span>虚拟桶名称</span><code>s3://{b.slug}</code><small>接入名称保持不变，避免应用配置失效。</small></div><BucketFormFields {...{name,setName,quota,setQuota,visibility,setVisibility,unlimited,setUnlimited,canUnlimited:detail.can_set_unlimited}}/><p className="field-explain">私有模式允许按次签发下载链接；公开映射模式还允许创建稳定的 /p/ 链接。真实存储源始终保持私有。</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="actions"><button type="button" className="ghost" disabled={busy} onClick={close}>取消</button><button className="primary" disabled={busy}>{busy?<Loader2 className="spin" size={17}/>:<ShieldCheck size={17}/>}保存调整</button></div></form></Modal>{confirmPrivate&&<RiskDialog eyebrow="PUBLIC LINK AVAILABILITY" title="将桶改为私有模式？" lead={b.slug} busy={busy} cancelLabel="继续检查" confirmLabel="停止公开映射并保存" onCancel={()=>setConfirmPrivate(false)} onConfirm={()=>void save()}><div className="risk-impact"><strong>现有 /p/ 公开别名将立即停止跳转</strong><p>应用仍可使用有 read 权限的虚拟凭据按次申请下载签名；已签发的真实 S3 URL 会按原有效期继续工作。</p>{error&&<p className="form-error" role="alert">{error}</p>}</div></RiskDialog>}</>;
}
function CreateBucket({api,canUnlimited,close,done}:{api:API;canUnlimited:boolean;close:()=>void;done:(v:any)=>void}){const[name,setName]=useState('');const[slug,setSlug]=useState('');const[quota,setQuota]=useState(10);const[visibility,setVisibility]=useState('private');const[unlimited,setUnlimited]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');return <Modal title="创建虚拟桶" close={close}><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{done(await api.createBucket({name,slug,visibility,quota_bytes:unlimited?0:quota*(1<<30),quota_unlimited:unlimited}))}catch(e:any){setError(e.message);setBusy(false)}}}><label>虚拟桶名称<div className="input-prefix"><span>s3://</span><input required value={slug} onChange={e=>setSlug(e.target.value)} placeholder="media-assets"/></div></label><BucketFormFields {...{name,setName,quota,setQuota,visibility,setVisibility,unlimited,setUnlimited,canUnlimited}}/><div className="hint"><ShieldCheck size={17}/><span>真实存储始终保持私有。公开映射模式允许稳定 /p/ 链接；私有模式仅允许按次签发下载链接。</span></div>{error&&<p className="form-error">{error}</p>}<div className="actions"><button type="button" className="ghost" onClick={close}>取消</button><button className="primary" disabled={busy}>{busy?<Loader2 className="spin" size={17}/>:<Plus size={17}/>}创建并签发凭据</button></div></form></Modal>}
function OneTimeSecret({data,close}:{data:any;close:()=>void}){return <Modal title="保存桶凭据" close={close} dismissible={false}><div className="once"><div className="warning"><KeyRound/><div><strong>仅显示这一次</strong><p>关闭后平台不会再次返回 Secret Key。</p></div></div><Field label="Access Key" value={data.access_key}/><Field label="Secret Key" value={data.secret_key}/><p>建议通过 rvsctl 直接写入部署环境的 Secret，而不是复制给 Agent。</p><button className="primary full" onClick={close}>我已安全保存</button></div></Modal>}
function Field({label,value}:{label:string;value:string}){return <label className="secret-field"><span>{label}</span><div><code>{value}</code><CopyButton text={value}/></div></label>}
function AccessPage({token}:{token:string}){
  const d=useData(token,'access');const[open,setOpen]=useState(false);const[secret,setSecret]=useState<any>();const[busy,setBusy]=useState('');const[risk,setRisk]=useState<AccessKey|null>(null);const[riskError,setRiskError]=useState('');
  if(d.loading&&!secret)return <Loading/>;if(d.error&&!secret)return <ErrorBox text={d.error} retry={d.reload}/>;
  const confirmRevoke=async()=>{if(!risk)return;setBusy(risk.id);try{await d.api.revokeKey(risk.id);setRisk(null);d.reload()}catch(e:any){setRiskError(e.message||'撤销失败，请重试')}finally{setBusy('')}};
  return <><div className="section-head"><div><p className="eyebrow">IDENTITIES & GRANTS</p><h2>访问控制</h2><p>密钥按桶签发，可单独撤销并限制读、写、删除和管理权限。</p></div><button className="primary small" disabled={!d.buckets.length} onClick={()=>setOpen(true)}><Plus size={16}/>签发访问密钥</button></div><article className="card table-card"><table><thead><tr><th>名称</th><th>虚拟桶</th><th>Access Key</th><th>权限</th><th>状态 / 操作</th></tr></thead><tbody>{d.keys.map(k=><tr key={k.id}><td><strong>{k.name}</strong></td><td><code>{k.bucket}</code></td><td><code>{k.access_key.slice(0,10)}••••</code></td><td><div className="tags">{k.permissions.map(p=><span key={p}>{p}</span>)}</div></td><td>{k.revoked?<span className="status off"><i/>已撤销</span>:<button className="revoke" disabled={busy===k.id} onClick={()=>{setRisk(k);setRiskError('')}}>{busy===k.id?<Loader2 className="spin" size={13}/>:<X size={13}/>}撤销</button>}</td></tr>)}</tbody></table>{!d.keys.length&&<Empty title="暂无访问密钥" text="创建虚拟桶时会自动签发 Owner 密钥。"/>}</article><div className="callout"><ShieldCheck/><div><strong>关于已经签发的真实 S3 链接</strong><p>撤销 AK/SK 会阻止新的签名请求，不会撤销已生成的 URL。对单个对象执行“立即失效”时，平台会在 S3 内部复制到新物理键并删除旧键，使旧 URL 立即返回 404。</p></div></div>{open&&<CreateAccessKey api={d.api} buckets={d.buckets} close={()=>setOpen(false)} done={v=>{setSecret(v);setOpen(false);d.reload()}}/>}{secret&&<OneTimeSecret data={secret} close={()=>setSecret(undefined)}/>} {risk&&<RiskDialog eyebrow="CREDENTIAL REVOCATION" title="确认撤销访问密钥" lead={risk.name} busy={busy===risk.id} cancelLabel="保留密钥" confirmLabel="撤销密钥" onCancel={()=>{setRisk(null);setRiskError('')}} onConfirm={confirmRevoke}><div className="risk-impact"><strong>应用将无法再申请新链接</strong><p>此密钥的所有权限会立即失效。已经签发的真实 S3 URL 会继续工作到各自的到期时间。</p>{riskError&&<p className="form-error" role="alert">{riskError}</p>}</div></RiskDialog>}</>;
}
function CreateAccessKey({api,buckets,close,done}:{api:API;buckets:Bucket[];close:()=>void;done:(v:any)=>void}){const[name,setName]=useState('应用访问');const[bucket,setBucket]=useState(buckets[0]?.slug||'');const[permissions,setPermissions]=useState(['read']);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const toggle=(p:string)=>setPermissions(v=>v.includes(p)?v.filter(x=>x!==p):[...v,p]);return <Modal title="签发访问密钥" close={close}><form className="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{done(await api.createKey(bucket,{name,permissions}))}catch(e:any){setError(e.message);setBusy(false)}}}><label>密钥名称<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>虚拟桶<select value={bucket} onChange={e=>setBucket(e.target.value)}>{buckets.map(b=><option key={b.id} value={b.slug}>{b.name} · {b.slug}</option>)}</select></label><label>细粒度权限<div className="permission-grid">{[['read','只读 / 下载'],['write','写入 / 上传'],['delete','删除对象'],['manage','管理链接']].map(([p,label])=><button type="button" key={p} className={permissions.includes(p)?'active':''} onClick={()=>toggle(p)}><ShieldCheck size={15}/><span>{label}<small>{p}</small></span></button>)}</div></label>{error&&<p className="form-error">{error}</p>}<div className="actions"><button type="button" className="ghost" onClick={close}>取消</button><button className="primary" disabled={busy||!permissions.length}>{busy?<Loader2 className="spin" size={17}/>:<KeyRound size={17}/>}签发密钥</button></div></form></Modal>}
function AgentPage({token,notify}:{token:string;notify:(s:string)=>void}){
  const api=useMemo(()=>new API(token),[token]);
  const[name,setName]=useState('新应用接入');
  const[quota,setQuota]=useState(10);
  const[minutes,setMinutes]=useState(30);
  const[result,setResult]=useState<any>();
  const[busy,setBusy]=useState(false);
  const[error,setError]=useState('');
  useVersionHold(Boolean(result));
  const prompt=result?buildAgentPrompt({gateway:location.origin,token:result.token,quotaGB:quota,expiresAt:result.expires_at,projectURL:result.project_url,releaseURL:result.release_url}):'';
  const generate=async()=>{
    setBusy(true);setError('');
    try{const response=await api.bootstrap({name,max_quota_bytes:quota*(1<<30),expires_in:minutes*60});setResult(response);notify('一次性 Agent 提示词已生成')}
    catch(e:any){setError(e.message||'生成失败，请重试')}
    finally{setBusy(false)}
  };
  return <><div className="section-head"><div><p className="eyebrow">AGENT ONBOARDING</p><h2>把接入说明交给 Agent</h2><p>创建一次性临时令牌，自动组成可复制的接入提示词。</p></div></div><div className="agent-layout"><article className="card form-card"><div className="step"><span>01</span><div><strong>临时授权范围</strong><p>令牌只能使用一次，并受空间和时间限制。</p></div></div><div className="form"><label>用途<input value={name} onChange={e=>setName(e.target.value)}/></label><div className="split"><label>最大空间（GB）<input type="number" min="1" value={quota} onChange={e=>setQuota(+e.target.value)}/></label><label>令牌有效期（分钟）<input type="number" min="1" value={minutes} onChange={e=>setMinutes(+e.target.value)}/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary full" disabled={busy||Boolean(result)||quota<1||minutes<1} onClick={generate}>{busy?<Loader2 className="spin" size={17}/>:<Sparkles size={17}/>}生成一次性接入提示词</button>{result&&<button className="ghost full" onClick={()=>setResult(undefined)}>已安全保存，准备生成下一份</button>}</div></article><article className="prompt-card"><div className="prompt-head"><div><span>AGENT PROMPT</span><strong>{result?'已包含一次性授权':'等待生成'}</strong></div>{result&&<CopyButton text={prompt} label="一键复制"/>}</div>{result?<pre>{prompt}</pre>:<div className="prompt-empty"><Sparkles/><p>生成后，完整接入说明会出现在这里。</p><small>Secret Key 将由 CLI 直接写入目标配置，不在终端回显。</small></div>}</article></div><div className="callout warm"><KeyRound/><div><strong>“Agent 不接触明文”是一条部署边界</strong><p>rvsctl 可以避免凭据出现在对话和终端输出中；拥有目标机器完整文件读取权的 Agent 仍可能读取 Secret。生产环境建议让 rvsctl 直接写入 Kubernetes Secret、Vault 或云端 Secret Manager，并限制 Agent 对 Secret 的读权限。</p></div></div></>;
}

const py=`import requests\n\n# 由应用明确决定这一次签名的有效期\nr = requests.post(\n  f"{GATEWAY}/api/v1/buckets/{BUCKET}/objects/download",\n  headers={\n    "X-RVS-Access-Key": ACCESS_KEY,\n    "X-RVS-Secret-Key": SECRET_KEY,\n  },\n  json={"key": "reports/q3.pdf", "expires_in": 900},\n)\n# 返回真实私有桶的预签名 URL；文件不经过平台\ndirect_url = r.json()["url"]`;
const upload=`# 不要对 VirSree /s3 端点调用 PutObject\n\n# 1. 向集中网关申请直传地址（应用选择 10 分钟）\nPOST /api/v1/buckets/media/objects/upload\n{\n  "key": "images/cover.webp",\n  "size": 284190,\n  "content_type": "image/webp",\n  "expires_in": 600\n}\n\n# 2. PUT 文件到响应中的真实 S3 URL\n# 3. 调用响应中的 commit_url 确认上传`;
function DocsPage(){const[tab,setTab]=useState<'download'|'upload'|'s3'>('download');const code=tab==='download'?py:tab==='upload'?upload:`AWS_ENDPOINT_URL=https://storage.example.com/s3\nAWS_ACCESS_KEY_ID=RVS...\nAWS_SECRET_ACCESS_KEY=<installed by rvsctl>\nAWS_REGION=us-east-1\n\n# ListObjectsV2、HEAD、GET、DELETE 使用标准 S3 SigV4。\n# 不要向此端点调用 PutObject；上传使用签名 URL 三步流程。`;return <><div className="section-head"><div><p className="eyebrow">ONE GATEWAY</p><h2>接入文档</h2><p>管理、Agent、S3 和签名请求全部进入同一个网关地址。</p></div></div><div className="docs-layout"><aside className="toc"><strong>快速开始</strong><a className="active">架构与约束</a><a>下载直链</a><a>上传直传</a><a>S3 SDK</a><strong>安全与运维</strong><a>链接失效</a><a>配额与预留</a><a>密钥轮换</a></aside><div><article className="doc-intro"><h3>一次接入，保留熟悉的 S3 心智</h3><p>应用只持有虚拟 AK/SK，不知道真实桶凭据。所有控制请求经过 VirSree 网关；网关签发真实 S3 URL 后，文件数据直接在应用与 S3 之间传输。上传必须先申请签名，不能向网关直接 PutObject。</p><div className="flow-row doc"><div>你的应用<small>S3 SDK / REST</small></div><i/><div className="accent">集中网关<small>统一策略与审计</small></div><i className="dashed"/><div>Private S3<small>直传文件字节</small></div></div></article><article className="code-card"><div className="code-tabs"><button className={tab==='download'?'active':''} onClick={()=>setTab('download')}>下载签名</button><button className={tab==='upload'?'active':''} onClick={()=>setTab('upload')}>上传直传</button><button className={tab==='s3'?'active':''} onClick={()=>setTab('s3')}>S3 配置</button><CopyButton text={code}/></div><pre>{code}</pre></article><article className="doc-note"><strong>有效期完全由应用指定</strong><p>每次签名请求必须提交 <code>expires_in</code>。平台不设置业务默认值，只遵守底层 SigV4 的协议硬上限（AWS S3 为 604800 秒）。</p></article></div></div></>}
function SettingsPage({token}:{token:string}){const d=useData(token,'overview');if(d.loading)return <Loading/>;if(d.error)return <ErrorBox text={d.error} retry={d.reload}/>;return <><div className="section-head"><div><p className="eyebrow">GATEWAY GOVERNANCE</p><h2>平台设置</h2><p>集中入口为后续策略、审计和流量治理保留统一边界。</p></div></div><div className="settings-grid"><article className="card setting"><div className="setting-icon"><Cloud/></div><div><span>真实存储后端</span><strong>{d.overview?.backend_ready?'连接配置完整':'等待配置'}</strong><p>对象由已验证的 S3 / WebDAV 存储源承载；S3 真实桶始终保持私有。</p></div><span className={`status ${d.overview?.backend_ready?'':'off'}`}><i/>{d.overview?.backend_ready?'Ready':'Not ready'}</span></article><article className="card setting"><div className="setting-icon"><Activity/></div><div><span>集中网关</span><strong>{location.origin}</strong><p><code>/api/v1</code>、<code>/s3</code>、<code>/p</code> 共用入口。</p></div><span className="status"><i/>Online</span></article><article className="card setting"><div className="setting-icon"><Database/></div><div><span>平台总空间</span><strong>{fmt(d.overview?.total_quota)}</strong><p>有限容量时按平台和存储源配额约束；无限容量需最高优先级存储源支持。</p></div></article><article className="card setting"><div className="setting-icon"><ShieldCheck/></div><div><span>链接撤销策略</span><strong>短期签名 + 物理键轮换</strong><p>AK 轮换阻止新签名；对象键轮换使旧直链立即失效。</p></div></article></div></>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><div><Box/></div><h3>{title}</h3><p>{text}</p></div>}
function Modal({title,close,children,dismissible=true}:{title:string;close:()=>void;children:any;dismissible?:boolean}){useVersionHold();return <div className="modal-bg"><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h3>{title}</h3>{dismissible&&<button aria-label="关闭对话框" onClick={close}><X/></button>}</div>{children}</div></div>}
function CopyButton({text,label}:{text:string;label?:string}){const[status,setStatus]=useState('');return <button type="button" className="copy" onClick={async()=>{try{await navigator.clipboard.writeText(text);setStatus('已复制')}catch{setStatus('复制失败')}setTimeout(()=>setStatus(''),1800)}}><Copy size={14}/>{status||label||''}</button>}
